name: my_nthu_life
description: "A student productivity app for NTHU life."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  # UI and Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2
  
  # Data and Logic
  form_field_validator: ^1.1.0
  shared_preferences: ^2.5.4
  
  # AI Summary Features
  file_picker: ^8.0.0
  syncfusion_flutter_pdf: ^21.1.35
  dart_openai: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Ensure your assets folder exists in your project root!
  assets:
    - assets/