// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtli0_7BdwQVoxn69oLKyVUZvR-dN1W4c',
    appId: '1:40087704428:web:4c922d143caa1af7881949',
    messagingSenderId: '40087704428',
    projectId: 'nthyou-eee75',
    authDomain: 'nthyou-eee75.firebaseapp.com',
    storageBucket: 'nthyou-eee75.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZJLkxijsBFqh6EbwuunMhn3PYT3o3dXw',
    appId: '1:40087704428:android:25f8ad664cdcead8881949',
    messagingSenderId: '40087704428',
    projectId: 'nthyou-eee75',
    storageBucket: 'nthyou-eee75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJWbHl3lumKBBYD40wa4On5AA6_AV6sl4',
    appId: '1:40087704428:ios:0e2e1bcecfd585e8881949',
    messagingSenderId: '40087704428',
    projectId: 'nthyou-eee75',
    storageBucket: 'nthyou-eee75.firebasestorage.app',
    iosBundleId: 'com.example.myNthuLife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJWbHl3lumKBBYD40wa4On5AA6_AV6sl4',
    appId: '1:40087704428:ios:0e2e1bcecfd585e8881949',
    messagingSenderId: '40087704428',
    projectId: 'nthyou-eee75',
    storageBucket: 'nthyou-eee75.firebasestorage.app',
    iosBundleId: 'com.example.myNthuLife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtli0_7BdwQVoxn69oLKyVUZvR-dN1W4c',
    appId: '1:40087704428:web:0da6a71939e3ee97881949',
    messagingSenderId: '40087704428',
    projectId: 'nthyou-eee75',
    authDomain: 'nthyou-eee75.firebaseapp.com',
    storageBucket: 'nthyou-eee75.firebasestorage.app',
  );
}
