import 'dart:async';
import 'dart:convert';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:provider/provider.dart';
import 'package:my_nthu_life/services/ai_service.dart';
import 'package:my_nthu_life/pet_files/pet_provider.dart';

class ProfessorPersonaScreen extends StatefulWidget {
  final String studentID;
  const ProfessorPersonaScreen({super.key, required this.studentID});

  @override
  State<ProfessorPersonaScreen> createState() => _ProfessorPersonaScreenState();
}

class _ProfessorPersonaScreenState extends State<ProfessorPersonaScreen> {
  final TextEditingController _projectNameController = TextEditingController(text: "Smart Campus Companion");
  final TextEditingController _courseNameController = TextEditingController(text: "Software Studio");
  final TextEditingController _docController = TextEditingController();
  final TextEditingController _chatInputController = TextEditingController();
  final ScrollController _chatScrollController = ScrollController();

  String _selectedProfessor = "Prof. Wang (The Socratic Sage)";
  final List<String> _professors = [
    "Prof. Wang (The Socratic Sage)",
    "Prof. Lin (The Pragmatic Veteran)"
  ];

  // Ingestion Phase States
  bool _isAutoGeneratingDoc = false;
  bool _isStartingDefense = false;

  // Active Presentation States
  bool _isDefenseActive = false;
  List<Map<String, String>> _chatHistory = []; // role: 'professor' or 'student', content: '...'
  bool _isProfessorThinking = false;

  // Real-time Diagnostic Telemetry States
  int _cognitiveSyncLevel = 50; // starts at 50, goes up/down
  List<String> _detectedWeaknesses = [];
  int _turnsCount = 0;

  // Final Report Card States
  bool _isGrading = false;
  Map<String, dynamic>? _gradeReport; // final grades from AIService

  @override
  void dispose() {
    _projectNameController.dispose();
    _courseNameController.dispose();
    _docController.dispose();
    _chatInputController.dispose();
    _chatScrollController.dispose();
    super.dispose();
  }

  Future<void> _autoGenerateDoc() async {
    final proj = _projectNameController.text.trim();
    final course = _courseNameController.text.trim();
    if (proj.isEmpty || course.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text("Please fill Project Name and Course Name first!"),
          backgroundColor: Colors.amber,
        ),
      );
      return;
    }

    setState(() => _isAutoGeneratingDoc = true);
    try {
      final res = await AIService.generateProjectDocMock(projectName: proj, courseName: course);
      if (res.containsKey('documentation')) {
        setState(() {
          _docController.text = res['documentation'] ?? "";
        });
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text("✨ Mock technical documentation compiled for $proj!"),
            backgroundColor: Colors.purpleAccent,
          ),
        );
      }
    } catch (e) {
      print("Error autogenerating doc: $e");
    } finally {
      setState(() => _isAutoGeneratingDoc = false);
    }
  }

  Future<void> _initiateDefense() async {
    final proj = _projectNameController.text.trim();
    final course = _courseNameController.text.trim();
    final docText = _docController.text.trim();

    if (proj.isEmpty || course.isEmpty || docText.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text("All fields (Project, Course, and Documentation) are required to feed the professor!"),
          backgroundColor: Colors.amber,
        ),
      );
      return;
    }

    setState(() => _isStartingDefense = true);
    try {
      final res = await AIService.startProfessorInterview(
        projectName: proj,
        courseName: course,
        projectDocText: docText,
        professorStyle: _selectedProfessor,
      );

      if (res.containsKey('question')) {
        setState(() {
          _chatHistory = [
            {'role': 'professor', 'content': res['question'] ?? ""}
          ];
          _cognitiveSyncLevel = res['score_progress'] ?? 50;
          _detectedWeaknesses = [res['detected_weakness'] ?? "Initial defense launched"];
          _turnsCount = 1;
          _isDefenseActive = true;
        });
      }
    } catch (e) {
      print("Error starting professor defense: $e");
    } finally {
      setState(() => _isStartingDefense = false);
    }
  }

  Future<void> _submitResponse() async {
    final responseText = _chatInputController.text.trim();
    if (responseText.isEmpty || _isProfessorThinking) return;

    setState(() {
      _chatHistory.add({'role': 'student', 'content': responseText});
      _chatInputController.clear();
      _isProfessorThinking = true;
    });

    _scrollToBottom();

    try {
      final res = await AIService.evaluateAndGenerateNextQuestion(
        projectName: _projectNameController.text.trim(),
        courseName: _courseNameController.text.trim(),
        projectDocText: _docController.text.trim(),
        professorStyle: _selectedProfessor,
        chatHistory: _chatHistory,
      );

      if (res.containsKey('next_question')) {
        setState(() {
          _chatHistory.add({'role': 'professor', 'content': res['next_question'] ?? ""});
          
          final scoreDelta = res['score_delta'] as int? ?? 0;
          _cognitiveSyncLevel = (_cognitiveSyncLevel + scoreDelta).clamp(0, 100);

          final weakness = res['detected_weakness'] as String? ?? "";
          if (weakness.isNotEmpty && !_detectedWeaknesses.contains(weakness)) {
            _detectedWeaknesses.add(weakness);
          }
          
          _turnsCount++;
          _isProfessorThinking = false;
        });
        _scrollToBottom();
      }
    } catch (e) {
      print("Error responding in professor interview: $e");
      setState(() => _isProfessorThinking = false);
    }
  }

  Future<void> _concludeDefense() async {
    final confirm = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        backgroundColor: Theme.of(context).colorScheme.surfaceContainerHigh,
        title: Text(
          "CONCLUDE ORAL EXAM",
          style: GoogleFonts.orbitron(
            fontSize: 14,
            fontWeight: FontWeight.bold,
            letterSpacing: 1.2,
          ),
        ),
        content: const Text("Are you ready to submit your transcript and request formal grading from the faculty professor?"),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context, false),
            child: const Text("CANCEL"),
          ),
          TextButton(
            onPressed: () => Navigator.pop(context, true),
            child: const Text("SUBMIT FOR GRADING"),
          ),
        ],
      ),
    );

    if (confirm != true) return;

    setState(() => _isGrading = true);

    try {
      final res = await AIService.generateFinalGradeReport(
        projectName: _projectNameController.text.trim(),
        courseName: _courseNameController.text.trim(),
        professorStyle: _selectedProfessor,
        chatHistory: _chatHistory,
      );

      if (res.containsKey('grade')) {
        setState(() {
          _gradeReport = res;
          _isGrading = false;
        });

        final bool passed = res['passed'] as bool? ?? false;
        if (passed) {
          // Award Gamified growth points to pet & user
          Provider.of<PetProvider>(context, listen: false)
              .awardGrowthPoints(studentID: widget.studentID, exp: 30, coins: 15);

          await FirebaseFirestore.instance
              .collection('users')
              .doc(widget.studentID)
              .set({
                'weeklyXP': FieldValue.increment(30),
              }, SetOptions(merge: true));
        }
      }
    } catch (e) {
      print("Error during grade generation: $e");
      setState(() => _isGrading = false);
    }
  }

  void _scrollToBottom() {
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (_chatScrollController.hasClients) {
        _chatScrollController.animateTo(
          _chatScrollController.position.maxScrollExtent,
          duration: const Duration(milliseconds: 300),
          curve: Curves.easeOut,
        );
      }
    });
  }

  void _resetSession() {
    setState(() {
      _isDefenseActive = false;
      _chatHistory = [];
      _cognitiveSyncLevel = 50;
      _detectedWeaknesses = [];
      _turnsCount = 0;
      _gradeReport = null;
      _docController.clear();
    });
  }

  @override
  Widget build(BuildContext context) {
    final cs = Theme.of(context).colorScheme;

    if (_isStartingDefense) {
      return _buildLoadingScreen(cs, "LAUNCHING INTERACTIVE SIMULATOR", "Professor is establishing the cognitive sync link and preparing final oral defense telemetry...");
    }

    if (_isGrading) {
      return _buildLoadingScreen(cs, "COMPILING ACADEMIC REVIEW", "Faculty is evaluating the dialogue transcript and preparing the formal university Grade Report...");
    }

    if (_gradeReport != null) {
      return _buildGradeReportCard(cs);
    }

    return Scaffold(
      backgroundColor: cs.surface,
      appBar: AppBar(
        backgroundColor: cs.surface,
        elevation: 0,
        leading: IconButton(
          icon: Icon(Icons.arrow_back_ios_new_rounded, color: cs.onSurface),
          onPressed: () => Navigator.pop(context),
        ),
        title: Text(
          "PROFESSOR PERSONA",
          style: GoogleFonts.orbitron(
            fontSize: 15,
            fontWeight: FontWeight.bold,
            color: cs.onSurface,
            letterSpacing: 1.5,
          ),
        ),
        centerTitle: true,
      ),
      body: SafeArea(
        child: _isDefenseActive ? _buildInterviewRoom(cs) : _buildConfigForm(cs),
      ),
    );
  }

  Widget _buildLoadingScreen(ColorScheme cs, String header, String body) {
    return Scaffold(
      backgroundColor: cs.surface,
      body: Center(
        child: Padding(
          padding: const EdgeInsets.all(32.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              const SizedBox(
                height: 80,
                width: 80,
                child: CircularProgressIndicator(
                  strokeWidth: 3,
                  color: Colors.purpleAccent,
                ),
              ),
              const SizedBox(height: 32),
              Text(
                header,
                style: GoogleFonts.orbitron(
                  fontSize: 15,
                  fontWeight: FontWeight.bold,
                  color: Colors.purpleAccent,
                  letterSpacing: 2,
                ),
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: 12),
              Text(
                body,
                style: GoogleFonts.outfit(
                  fontSize: 12,
                  color: cs.onSurfaceVariant,
                  height: 1.5,
                ),
                textAlign: TextAlign.center,
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildConfigForm(ColorScheme cs) {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(20),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Banner explanation
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              gradient: LinearGradient(
                colors: [cs.primaryContainer.withOpacity(0.12), cs.surfaceContainerLow],
              ),
              borderRadius: BorderRadius.circular(16),
              border: Border.all(color: cs.primaryContainer.withOpacity(0.3)),
            ),
            child: Row(
              children: [
                Icon(Icons.school_rounded, color: cs.primaryContainer, size: 28),
                const SizedBox(width: 14),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        "ORAL EXAM INTERPRETER",
                        style: GoogleFonts.orbitron(
                          fontSize: 13,
                          fontWeight: FontWeight.bold,
                          color: cs.primaryContainer,
                          letterSpacing: 1,
                        ),
                      ),
                      const SizedBox(height: 4),
                      Text(
                        "Submit technical documentation. The NTHU faculty persona will grill you with custom multi-turn questions, tracking weaknesses on a real-time scanner.",
                        style: GoogleFonts.outfit(fontSize: 11, color: cs.onSurfaceVariant),
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ),
          const SizedBox(height: 24),

          // Fields
          Text(
            "PROJECT NAME",
            style: GoogleFonts.orbitron(
              fontSize: 11,
              fontWeight: FontWeight.bold,
              color: cs.primaryContainer,
              letterSpacing: 1,
            ),
          ),
          const SizedBox(height: 8),
          TextField(
            controller: _projectNameController,
            style: GoogleFonts.outfit(fontSize: 13),
            decoration: InputDecoration(
              filled: true,
              fillColor: cs.surfaceContainerLow,
              border: OutlineInputBorder(borderRadius: BorderRadius.circular(10)),
            ),
          ),
          const SizedBox(height: 20),

          Text(
            "COURSE / DEPT",
            style: GoogleFonts.orbitron(
              fontSize: 11,
              fontWeight: FontWeight.bold,
              color: cs.primaryContainer,
              letterSpacing: 1,
            ),
          ),
          const SizedBox(height: 8),
          TextField(
            controller: _courseNameController,
            style: GoogleFonts.outfit(fontSize: 13),
            decoration: InputDecoration(
              filled: true,
              fillColor: cs.surfaceContainerLow,
              border: OutlineInputBorder(borderRadius: BorderRadius.circular(10)),
            ),
          ),
          const SizedBox(height: 20),

          Text(
            "SELECT PROFESSOR PERSONA",
            style: GoogleFonts.orbitron(
              fontSize: 11,
              fontWeight: FontWeight.bold,
              color: cs.primaryContainer,
              letterSpacing: 1,
            ),
          ),
          const SizedBox(height: 10),
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 4),
            decoration: BoxDecoration(
              color: cs.surfaceContainerLow,
              borderRadius: BorderRadius.circular(10),
              border: Border.all(color: cs.outlineVariant),
            ),
            child: DropdownButtonHideUnderline(
              child: DropdownButton<String>(
                value: _selectedProfessor,
                isExpanded: true,
                dropdownColor: cs.surfaceContainerHigh,
                items: _professors.map((prof) {
                  return DropdownMenuItem<String>(
                    value: prof,
                    child: Text(
                      prof,
                      style: GoogleFonts.outfit(fontSize: 13, fontWeight: FontWeight.bold),
                    ),
                  );
                }).toList(),
                onChanged: (val) {
                  setState(() => _selectedProfessor = val!);
                },
              ),
            ),
          ),
          const SizedBox(height: 24),

          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(
                "PROJECT BLUEPRINT / ARCHITECTURE",
                style: GoogleFonts.orbitron(
                  fontSize: 11,
                  fontWeight: FontWeight.bold,
                  color: cs.primaryContainer,
                  letterSpacing: 1,
                ),
              ),
              _isAutoGeneratingDoc
                  ? const SizedBox(
                      width: 14,
                      height: 14,
                      child: CircularProgressIndicator(strokeWidth: 2, color: Colors.purpleAccent),
                    )
                  : InkWell(
                      onTap: _autoGenerateDoc,
                      child: Row(
                        children: [
                          const Icon(Icons.auto_fix_high_rounded, size: 14, color: Colors.purpleAccent),
                          const SizedBox(width: 4),
                          Text(
                            "AUTO-GENERATE",
                            style: GoogleFonts.orbitron(
                              fontSize: 10,
                              fontWeight: FontWeight.bold,
                              color: Colors.purpleAccent,
                            ),
                          ),
                        ],
                      ),
                    ),
            ],
          ),
          const SizedBox(height: 10),
          TextField(
            controller: _docController,
            maxLines: 8,
            style: GoogleFonts.outfit(fontSize: 12),
            decoration: InputDecoration(
              hintText: "Paste your architectural documentation, DB choices, stream structure, testing files...",
              hintStyle: GoogleFonts.outfit(color: cs.onSurfaceVariant.withOpacity(0.5), fontSize: 12),
              filled: true,
              fillColor: cs.surfaceContainerLow,
              border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
            ),
          ),
          const SizedBox(height: 32),

          SizedBox(
            width: double.infinity,
            child: ElevatedButton(
              style: ElevatedButton.styleFrom(
                backgroundColor: cs.primaryContainer,
                foregroundColor: Colors.white,
                padding: const EdgeInsets.symmetric(vertical: 16),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                elevation: 4,
              ),
              onPressed: _initiateDefense,
              child: Text(
                "LAUNCH ORAL PRESENTATION DEFENSE",
                style: GoogleFonts.orbitron(
                  fontSize: 11,
                  fontWeight: FontWeight.bold,
                  letterSpacing: 1.5,
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildInterviewRoom(ColorScheme cs) {
    final bool isWang = _selectedProfessor.contains("Wang");
    final IconData profIcon = isWang ? Icons.school_rounded : Icons.terminal_rounded;
    final Color telemetryColor = _cognitiveSyncLevel >= 75
        ? Colors.green
        : _cognitiveSyncLevel >= 45
            ? Colors.amber
            : Colors.redAccent;

    return Row(
      children: [
        // Real-Time Telemetry Sidebar (Interactive Multi-Turn Diagnostics)
        Container(
          width: 120,
          padding: const EdgeInsets.all(12),
          decoration: BoxDecoration(
            color: cs.surfaceContainerLow,
            border: Border(right: BorderSide(color: cs.outlineVariant, width: 1)),
          ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                "DIAGNOSTICS",
                style: GoogleFonts.orbitron(
                  fontSize: 9,
                  fontWeight: FontWeight.bold,
                  color: cs.primaryContainer,
                  letterSpacing: 1,
                ),
              ),
              const SizedBox(height: 20),

              // Cognitive Sync Circular Indicator
              Center(
                child: Column(
                  children: [
                    Stack(
                      alignment: Alignment.center,
                      children: [
                        SizedBox(
                          width: 60,
                          height: 60,
                          child: CircularProgressIndicator(
                            value: _cognitiveSyncLevel / 100.0,
                            color: telemetryColor,
                            backgroundColor: cs.surfaceContainerHighest,
                            strokeWidth: 4,
                          ),
                        ),
                        Text(
                          "$_cognitiveSyncLevel%",
                          style: GoogleFonts.orbitron(
                            fontSize: 11,
                            fontWeight: FontWeight.bold,
                            color: telemetryColor,
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 8),
                    Text(
                      "COGNITIVE SYNC",
                      style: GoogleFonts.orbitron(
                        fontSize: 7,
                        fontWeight: FontWeight.bold,
                        color: cs.onSurfaceVariant,
                      ),
                      textAlign: TextAlign.center,
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 24),

              Text(
                "ROUNDS: $_turnsCount/5",
                style: GoogleFonts.orbitron(
                  fontSize: 8,
                  fontWeight: FontWeight.bold,
                  color: cs.onSurface,
                ),
              ),
              const SizedBox(height: 24),

              // Detected weaknesses telemetry list
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      "GAPS IDENTIFIED",
                      style: GoogleFonts.orbitron(
                        fontSize: 8,
                        fontWeight: FontWeight.bold,
                        color: Colors.redAccent,
                        letterSpacing: 0.5,
                      ),
                    ),
                    const SizedBox(height: 8),
                    Expanded(
                      child: ListView.builder(
                        itemCount: _detectedWeaknesses.length,
                        itemBuilder: (context, idx) {
                          return Padding(
                            padding: const EdgeInsets.only(bottom: 6.0),
                            child: Row(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const Icon(Icons.warning_amber_rounded, size: 10, color: Colors.amber),
                                const SizedBox(width: 4),
                                Expanded(
                                  child: Text(
                                    _detectedWeaknesses[idx],
                                    style: GoogleFonts.outfit(
                                      fontSize: 8,
                                      color: cs.onSurfaceVariant,
                                      fontWeight: FontWeight.w600,
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          );
                        },
                      ),
                    ),
                  ],
                ),
              ),

              // End presentation early button
              SizedBox(
                width: double.infinity,
                child: ElevatedButton(
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.redAccent.withOpacity(0.15),
                    foregroundColor: Colors.redAccent,
                    elevation: 0,
                    padding: const EdgeInsets.symmetric(vertical: 8),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(6),
                      side: const BorderSide(color: Colors.redAccent, width: 1),
                    ),
                  ),
                  onPressed: _concludeDefense,
                  child: Text(
                    "CONCLUDE",
                    style: GoogleFonts.orbitron(
                      fontSize: 8,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),

        // Chat Space
        Expanded(
          child: Column(
            children: [
              // Chat List
              Expanded(
                child: ListView.builder(
                  controller: _chatScrollController,
                  padding: const EdgeInsets.all(16),
                  itemCount: _chatHistory.length + (_isProfessorThinking ? 1 : 0),
                  itemBuilder: (context, index) {
                    if (index == _chatHistory.length) {
                      return _buildThinkingBubble(cs, profIcon);
                    }

                    final msg = _chatHistory[index];
                    final bool isProf = msg['role'] == 'professor';

                    return Align(
                      alignment: isProf ? Alignment.centerLeft : Alignment.centerRight,
                      child: Container(
                        margin: const EdgeInsets.only(bottom: 16),
                        padding: const EdgeInsets.all(14),
                        constraints: const BoxConstraints(maxWidth: 240),
                        decoration: BoxDecoration(
                          color: isProf ? cs.surfaceContainerLow : cs.primaryContainer,
                          borderRadius: BorderRadius.only(
                            topLeft: const Radius.circular(14),
                            topRight: const Radius.circular(14),
                            bottomLeft: isProf ? Radius.zero : const Radius.circular(14),
                            bottomRight: isProf ? const Radius.circular(14) : Radius.zero,
                          ),
                          border: isProf
                              ? Border.all(
                                  color: isWang ? Colors.teal.withOpacity(0.3) : Colors.orange.withOpacity(0.3),
                                  width: 1.5,
                                )
                              : null,
                        ),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            if (isProf) ...[
                              Row(
                                children: [
                                  Icon(
                                    profIcon,
                                    size: 14,
                                    color: isWang ? Colors.tealAccent : Colors.orangeAccent,
                                  ),
                                  const SizedBox(width: 6),
                                  Text(
                                    isWang ? "Wang, Ph.D." : "Lin, Tech.D.",
                                    style: GoogleFonts.orbitron(
                                      fontSize: 9,
                                      fontWeight: FontWeight.bold,
                                      color: isWang ? Colors.tealAccent : Colors.orangeAccent,
                                    ),
                                  ),
                                ],
                              ),
                              const Divider(height: 12, color: Colors.white24),
                            ],
                            Text(
                              msg['content'] ?? "",
                              style: GoogleFonts.outfit(
                                fontSize: 12,
                                color: isProf ? cs.onSurface : Colors.white,
                                height: 1.4,
                              ),
                            ),
                          ],
                        ),
                      ),
                    );
                  },
                ),
              ),

              // Chat Input Field
              Container(
                padding: const EdgeInsets.all(12),
                decoration: BoxDecoration(
                  color: cs.surfaceContainerLow,
                  border: Border(top: BorderSide(color: cs.outlineVariant, width: 1)),
                ),
                child: Row(
                  children: [
                    Expanded(
                      child: TextField(
                        controller: _chatInputController,
                        style: GoogleFonts.outfit(fontSize: 12),
                        decoration: InputDecoration(
                          hintText: "Type technical justification...",
                          hintStyle: GoogleFonts.outfit(color: cs.onSurfaceVariant.withOpacity(0.5), fontSize: 12),
                          filled: true,
                          fillColor: cs.surfaceContainerLowest,
                          border: OutlineInputBorder(borderRadius: BorderRadius.circular(10)),
                          contentPadding: const EdgeInsets.symmetric(horizontal: 14, vertical: 10),
                        ),
                        onSubmitted: (_) => _submitResponse(),
                      ),
                    ),
                    const SizedBox(width: 8),
                    IconButton(
                      icon: const Icon(Icons.send_rounded, color: Colors.purpleAccent),
                      onPressed: _submitResponse,
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }

  Widget _buildThinkingBubble(ColorScheme cs, IconData icon) {
    final bool isWang = _selectedProfessor.contains("Wang");
    return Align(
      alignment: Alignment.centerLeft,
      child: Container(
        margin: const EdgeInsets.only(bottom: 16),
        padding: const EdgeInsets.all(12),
        decoration: BoxDecoration(
          color: cs.surfaceContainerLow,
          borderRadius: BorderRadius.circular(14),
          border: Border.all(
            color: isWang ? Colors.teal.withOpacity(0.3) : Colors.orange.withOpacity(0.3),
          ),
        ),
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(icon, size: 14, color: isWang ? Colors.tealAccent : Colors.orangeAccent),
            const SizedBox(width: 10),
            SizedBox(
              width: 12,
              height: 12,
              child: CircularProgressIndicator(
                strokeWidth: 2,
                color: isWang ? Colors.tealAccent : Colors.orangeAccent,
              ),
            ),
            const SizedBox(width: 10),
            Text(
              "Professor is scrutinizing logic...",
              style: GoogleFonts.orbitron(fontSize: 9, fontStyle: FontStyle.italic),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildGradeReportCard(ColorScheme cs) {
    final report = _gradeReport!;
    final String grade = report['grade'] ?? "B";
    final String evalText = report['overall_evaluation'] ?? "No evaluation details provided.";
    final List<dynamic> strengths = report['strengths'] ?? [];
    final List<dynamic> weaknesses = report['weaknesses'] ?? [];
    final bool passed = report['passed'] as bool? ?? false;

    return Scaffold(
      backgroundColor: cs.surface,
      appBar: AppBar(
        backgroundColor: cs.surface,
        elevation: 0,
        automaticallyImplyLeading: false,
        title: Text(
          "FACULTY TRANSCRIPT",
          style: GoogleFonts.orbitron(
            fontSize: 13,
            fontWeight: FontWeight.bold,
            letterSpacing: 1.2,
          ),
        ),
        centerTitle: true,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24),
        child: Column(
          children: [
            // Grade Seal / Badge
            Center(
              child: Container(
                padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),
                decoration: BoxDecoration(
                  color: passed ? Colors.green.withOpacity(0.12) : Colors.redAccent.withOpacity(0.12),
                  borderRadius: BorderRadius.circular(14),
                  border: Border.all(
                    color: passed ? Colors.green : Colors.redAccent,
                    width: 2.5,
                  ),
                ),
                child: Column(
                  children: [
                    Text(
                      grade,
                      style: GoogleFonts.orbitron(
                        fontSize: 48,
                        fontWeight: FontWeight.bold,
                        color: passed ? Colors.green : Colors.redAccent,
                      ),
                    ),
                    const SizedBox(height: 4),
                    Text(
                      passed ? "STATUS: PASSED (Sync Confirmed)" : "STATUS: REJECTED (Insufficient Sync)",
                      style: GoogleFonts.orbitron(
                        fontSize: 8,
                        fontWeight: FontWeight.bold,
                        color: passed ? Colors.green : Colors.redAccent,
                        letterSpacing: 1.2,
                      ),
                    ),
                  ],
                ),
              ),
            ),
            const SizedBox(height: 24),

            // Strengths and weaknesses lists
            if (strengths.isNotEmpty || weaknesses.isNotEmpty) ...[
              Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  if (strengths.isNotEmpty)
                    Expanded(
                      child: Container(
                        padding: const EdgeInsets.all(12),
                        decoration: BoxDecoration(
                          color: Colors.green.withOpacity(0.06),
                          borderRadius: BorderRadius.circular(10),
                          border: Border.all(color: Colors.green.withOpacity(0.2)),
                        ),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              "STRENGTHS",
                              style: GoogleFonts.orbitron(fontSize: 9, fontWeight: FontWeight.bold, color: Colors.green),
                            ),
                            const SizedBox(height: 8),
                            ...strengths.map((s) => Padding(
                                  padding: const EdgeInsets.only(bottom: 4.0),
                                  child: Text("• $s", style: GoogleFonts.outfit(fontSize: 10, color: cs.onSurface)),
                                )),
                          ],
                        ),
                      ),
                    ),
                  if (strengths.isNotEmpty && weaknesses.isNotEmpty) const SizedBox(width: 12),
                  if (weaknesses.isNotEmpty)
                    Expanded(
                      child: Container(
                        padding: const EdgeInsets.all(12),
                        decoration: BoxDecoration(
                          color: Colors.redAccent.withOpacity(0.06),
                          borderRadius: BorderRadius.circular(10),
                          border: Border.all(color: Colors.redAccent.withOpacity(0.2)),
                        ),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(
                              "CRITIQUE ARTIFACTS",
                              style: GoogleFonts.orbitron(fontSize: 9, fontWeight: FontWeight.bold, color: Colors.redAccent),
                            ),
                            const SizedBox(height: 8),
                            ...weaknesses.map((w) => Padding(
                                  padding: const EdgeInsets.only(bottom: 4.0),
                                  child: Text("• $w", style: GoogleFonts.outfit(fontSize: 10, color: cs.onSurface)),
                                )),
                          ],
                        ),
                      ),
                    ),
                ],
              ),
              const SizedBox(height: 24),
            ],

            // Text critique
            Container(
              width: double.infinity,
              padding: const EdgeInsets.all(18),
              decoration: BoxDecoration(
                color: cs.surfaceContainerLow,
                borderRadius: BorderRadius.circular(16),
                border: Border.all(color: cs.outlineVariant),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    children: [
                      const Icon(Icons.description_rounded, size: 16, color: Colors.purpleAccent),
                      const SizedBox(width: 8),
                      Text(
                        "OFFICIAL FACULTY TRANSCRIPT",
                        style: GoogleFonts.orbitron(
                          fontSize: 10,
                          fontWeight: FontWeight.bold,
                          color: Colors.purpleAccent,
                        ),
                      ),
                    ],
                  ),
                  const Divider(height: 20, color: Colors.white24),
                  Text(
                    evalText,
                    style: GoogleFonts.outfit(
                      fontSize: 12,
                      color: cs.onSurface,
                      height: 1.5,
                    ),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 32),

            // Action Close buttons
            Row(
              children: [
                Expanded(
                  child: ElevatedButton(
                    style: ElevatedButton.styleFrom(
                      backgroundColor: cs.primaryContainer,
                      foregroundColor: Colors.white,
                      padding: const EdgeInsets.symmetric(vertical: 14),
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
                    ),
                    onPressed: _resetSession,
                    child: Text(
                      "INITIATE NEW DEFENSE",
                      style: GoogleFonts.orbitron(
                        fontSize: 11,
                        fontWeight: FontWeight.bold,
                        letterSpacing: 1,
                      ),
                    ),
                  ),
                ),
                const SizedBox(width: 12),
                ElevatedButton(
                  style: ElevatedButton.styleFrom(
                    backgroundColor: cs.surfaceContainerHigh,
                    foregroundColor: cs.onSurface,
                    padding: const EdgeInsets.symmetric(vertical: 14, horizontal: 20),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10)),
                  ),
                  onPressed: () => Navigator.pop(context),
                  child: Text(
                    "LEAVE WAR ROOM",
                    style: GoogleFonts.orbitron(
                      fontSize: 11,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}
